message: Just a simple String bean in yaml file!!!!

spring:
  #To always initialize an SQL database, irrespective of its type, set spring.sql.init.mode to always.
  #Similarly, to disable initialization, set spring.sql.init.mode to never.
  sql:
    init:
      mode: never

  jackson:
    visibility.field: any
    visibility.getter: none
    visibility.setter: none
    visibility.is-getter: none

  data:
    rest:
      base-path: /api
      return-body-on-create: true

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch.size: 20
        id.new_generator_mappings: true

    defer-datasource-initialization: true


 # h2:
 #   console:
 #     enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #org.h2.Driver
    url: jdbc:mysql://localhost:3306/testdb  #jdbc:h2:mem:testdb
    username: sa
    password:

